### PR TITLE
Fixed dutch grammar exclusion

### PR DESCRIPTION
**Pull request by finwo**
Following the advice from #154, here's a fix for the Dutch locale

### CODE REVIEW

**Comment by hustcc** [comment]
please update the src/lang/nl.js, then add the testcase.

**Comment by finwo** [comment]
@hustcc To ensure a test for NL, I'd have to add it to the default locales (if I'm reading everything correct). Would you agree with that?

**Comment by hustcc** [comment]
Can see https://github.com/hustcc/timeago.js/blob/master/__tests__/lang/en.spec.js

**Comment by hustcc** [comment]
you can just push pr into master.

**Comment by finwo** [comment]
@hustcc Once I added the test, I'll change the target branch.

**Comment by hustcc** [comment]
All is done?

**Comment by finwo** [comment]
Correct, all is done.

**Pull request merged**
