### PR TITLE
Add Persian Localization

### PR DESCRIPTION
**Pull request by mamadoo**

### CODE REVIEW

**Comment by hustcc** [comment]
Pls fixed the travis-ci error. #19

**Comment by mamadoo** [comment]
I just translate en.js to fa.js.
Would you mind helping me to find errors?

**Comment by hustcc** [comment]
```
not ok 56 locale [fa]
  ---
    operator: ok
    expected: true
    actual:   false
    at: Test.<anonymous> (/home/travis/build/hustcc/timeago.js/tests/locales_test.js:13:16)
  ...
```

You can see the file, and you can run `npm run test` on your PC for testing.

**Comment by mamadoo** [comment]
Sorry, I can not find problem.
Forget about it.

**Comment by hustcc** [comment]
```js
+  t.equal(tb.subMinutes(1), '1 دقیقه قبل');
```

the locale will return `['1 دقیقه قبل', 'در 1 دقیقه'],`.

**Comment by hustcc** [comment]
Hi, any progress?

**Comment by mamadoo** [comment]
no, I cant understand your help, because even before any changes, there is still some error.

**Comment by hustcc** [comment]
Can you open the site https://travis-ci.org/hustcc/timeago.js/builds/217054489, you can see the testing errors in the page.

**Comment by mamadoo** [comment]
I clone your project again and do not anything and just run `npm run test`. This is result for test:

#tests 1179
#pass  1132
#fail  47

What's wrong?

**Comment by hustcc** [comment]
Can give one screenshot of the error in console.

**Comment by mamadoo** [comment]
Here you are:
p2

**Comment by hustcc** [comment]
I need the error message above the point.

image

**Comment by mamadoo** [comment]
These are 2 last error in console:
err2

**Comment by hustcc** [comment]
#136 has done. Thank you all the same.

**Pull request closed without merging**
