### PR TITLE
Added Georgian locale (ka_GE)

### PR DESCRIPTION
**Pull request by Lukakva**
Added translations for the Georgian language.

Although not very well known, Georgian is a unique language spoken only by the citizens of Republic of Georgia (for thousands of years).

I love your library, and since I had to create a Georgian locale for my use anyway, I thought I might as well create a PR.

Not a lot of libraries have Georgian translations, so your library will stand out even more now!

### CODE REVIEW

**Comment by hustcc** [comment]
Thank you very much.

Please help to fill the testease of the locale.

**Comment by Lukakva** [comment]
@hustcc There seems to be no language tests in v4.0.0 branch. Should I commit a test file in the master branch?

**Comment by hustcc** [comment]
There has one test case of en.

**Comment by hustcc** [comment]
send pr to master, code is merged into master.

**Comment by Lukakva** [comment]
Running `npm install` didn't install `jest-date-mock` since it was not included in `package.json`, so I added it. I hope that's okay.

**Comment by hustcc** [comment]
Seem you pr to timeago.js on branch v4.0.0, you should change to master.

**Comment by Lukakva** [comment]
Will open a new pull request, sorry for the inconvenience.

**Pull request closed without merging**
