### PR TITLE
Improve italian translation

### PR DESCRIPTION
**Pull request by renyhp**
See [my other merged PR at jquery-timeago](https://github.com/rmm5t/jquery-timeago/pull/345).

### CODE REVIEW

**Comment by hustcc** [comment]
Please help add the testease.

**Comment by renyhp** [comment]
I am willing to help but I'm not very familiar with js, so I'll need some more details about what I should do

**Comment by hustcc** [comment]
You can write it like `en`.

file here: https://github.com/hustcc/timeago.js/blob/master/__tests__/lang/en.spec.js

**Comment by renyhp** [comment]
Hoping I did it the right way, please tell me if I need to change anything.
Out of curiosity, what is this file for? (I have a feeling that it tests the locale, but I assume this feeling is wrong because I see no point in doing so.)

Oops, I see where I've failed. I'm on it.

**Comment by renyhp** [comment]
I can squash these commits if you like. I would have to open another PR in that case, though.

**Comment by hustcc** [comment]
squash them may be perfect.

**Pull request closed without merging**
