### PR TITLE
Add Korean locale

### PR DESCRIPTION
**Pull request by wooseopkim**
[](https://postimg.org/image/6fut6vg03/)

Above is the test result! Thank you.

### CODE REVIEW

**Comment by hustcc** [comment]
travis CI result: https://travis-ci.org/hustcc/timeago.js/builds/160624310

**Comment by wooseopkim** [comment]
Sorry, I missed some typos. Maybe I was too excited to contribute to this repo... Just fixed it. Should I make another branch, or is it okay to make one more commit to fix this?

**Comment by wooseopkim** [comment]
I made one more commit to fix this. I'm creating a new pull request with two commits. Let me know if you want them to be in one single commit.

**Comment by hustcc** [comment]
commr or commits all will be ok, thank you for your contribution.

**Pull request closed without merging**
