### PR TITLE
Add timeago.en.js with english default locale only

### LINKED ISSUE #80: Generate separate timeago.js with only english locale
It would be nice to have a generated `timeago.js` that only included the english as it's default locale. I am currently in a situation where I will not be using the chinese locale and would like to have them removed so that I can optimize the size of my third party dependencies. 

Imo, it would be easier to have this part of this repo rather than me having to maintain my own fork.

Something like `dist/timeago.en.js` with only english as the default locale would be perfect!

### PR DESCRIPTION
**Pull request by ClemMakesApps**
Creates a separate timeago.js build that only contains an english default locale using `gulp-strip-code`

timeago.js ~ 9.2kb
timeago.en.js ~ 8.8kb

timeago.min.js ~ 1.7kb
timeago.en.js ~ 1.5kb

Closes #80

### CODE REVIEW

**Comment by hustcc** [comment]
So how to use it ?

``` js
var timeagoInstance = new require('timeago.js/dist/timeago.en.js')();
timeagoInstance.format(date);
```

I think `new require('timeago.js');` will be more centralized.

If I generate a timeago with only one build-in locale `en`, this means other language also have to a seperate `timeago.<locale>.js`.

**Comment by ClemMakesApps** [comment]
`timeago.en.js` is the same as `timeago.js` except without the default chinese locale.

As for the naming convention, that can be changed 😄

**Comment by hustcc** [comment]
I means If I generate a timeago with only one build-in locale en, this means other language also have to a seperate timeago.<locale>.js.

timeago.en.js has no meaning for user, Instead, user maybe confused. I need to writie more readme for it.

**Comment by ClemMakesApps** [comment]
I can add a readme for it if you'd like. As mentioned before, I understand that the naming convention may not be the best and am up for suggestions 👍.

As for the reason of separating it, although I agree that having a version with chinese and english default locales should work for everyone. Imo, it would also make sense to have one that is just english only as there are also a lot of websites that only target the english language. Although the extra 200 bytes of data may not appear much in the grand scheme of things, it would be nice to optimize, so that we can be good stewards of our users bandwidths.

**Comment by likerRr** [comment]
@ClemMakesApps seriously, I can't get why it matters. If anyone needs these 200 bytes, he can fork the library and exclude Chinese locale and thus save some bytes. 

Similarly we can request a library version without `render` function, because when someone uses the library at server he never will use `render` method. But we don't.

So I don't think we need version with English locale only.

**Comment by ClemMakesApps** [comment]
@likerRr I understand your point and I was going to fork this feature but based on the discussions with @hustcc in #80, it seemed like this feature was a viable option for this repo.

I think there maybe other people like me who may benefit from this but ultimately, I'm okay if you decide that this is not the direction you'd like to go. I'm cool with maintaining my fork. Feel free to close this PR if so. There's no hard feelings about this 😄

**Comment by hustcc** [comment]
I also think there is no need to build a version with `en` only, if merge this pr, other locales may need a pr also.

So close it.

**Comment by ClemMakesApps** [comment]
If anyone is ever interested in this feature, please check out my repo on gitlab: https://gitlab.com/ClemMakesApps/timeago.js

Thanks @hustcc for taking the time to go through this discussion and PR.

**Pull request closed without merging**
