### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jennifer-Brigman**
I found a few adjustments to make to your README. md file for clarification of documentation.

### CODE REVIEW

**Comment by moubi** [comment]
Nice catches @Jennifer-Brigman

**Comment by Jennifer-Brigman** [comment]
@moubi Thank you! I'm glad to be able to help.

**Comment by hustcc** [comment]
Why closed ?

**Comment by Jennifer-Brigman** [comment]
I apologize, I was trained differently. Is that not the proper course once a commit is accepted?

Sent from my iPhone

On Sep 14, 2016, at 8:23 PM, hustcc <notifications@github.com<mailto:notifications@github.com>> wrote:

Why closed ?

**Pull request closed without merging**
