### PR TITLE
fix Dutch translation from `binnenkort` to `zojuist`

### PR DESCRIPTION
**Pull request by mvdwaeter**
This PR fixes a Dutch translation for timestamps that are less than 1 second ago.
The old translation "binnenkort" translates to "in the near future", which is wrong.
I changed it to "zojuist" which translates to "recent"

### CODE REVIEW

**Comment by mvdwaeter** [comment]
When accepted, is it possible to make a minor release for the v2, e.g. v2.0.6?
this would help me a lot :)

**Comment by hustcc** [comment]
Why not to upgrade to v4, just a little time 😂

**Comment by mvdwaeter** [comment]
If accepted, can this be released as 

> Why not to upgrade to v4, just a little time 😂

That's because timeago.js is a dependency, on a third-party software we use (coral-talk) that pins it's timeago.js dependency as:

    "timeago.js": "^2.0.3",

So a version 2.0.6 should automatically be picked up without writing a patch.

**Comment by mvdwaeter** [comment]
Actually, I just realised I made a mistake, there are two columns, one for "x seconds ago" and one for "within x seconds". Other than that, the error I was trying to fix regarded a timestamp from the server that was compared with a timestamp of the client. Hence, a discrepancy can exist, which results in timestamps from the past are seen as timestamp from the future..

**Pull request closed without merging**
