### PR TITLE
Update nl.js

### PR DESCRIPTION
**Pull request by dominicjordan**
Wrong use of language. Trust me, I'm a dutchy:)

### CODE REVIEW

**Comment by hustcc** [comment]
Sorry for late, Can you send the pr to new dev branch `v4.0.0`. Thank you~

**Comment by finwo** [comment]
@dominicjordan You forgot the ones for years. Both hours & years are an exclusion in the Dutch grammar.

Source: https://www.startpagina.nl/v/taal/vraag/73284/zeggen-twee-uur-geleden-twee/

**Comment by hustcc** [comment]
@dominicjordan please help me fix the conflict, thank you ~

@finwo Can you do something to help?

**Comment by finwo** [comment]
@dominicjordan Something like a PR to dev v4.0.0?

**Pull request closed without merging**
