### PR TITLE
Ajphukan upload 1

### PR DESCRIPTION
**Pull request by ajphukan**
#19 PR for adding ind_hin (Hindi) in locale folder

### CODE REVIEW

**Comment by hustcc** [comment]
Thank you for your nice work, is `ind_hin` is the right locale key of Hindi?

The locale key maybe always with the format like `[a-z]{2}_[A-Z]{2}`.

**Comment by ajphukan** [comment]
I don't know the locale key and it was not in the list too . So , I just made it .. Is there is a limit in the length of local keyword ...

can you suggest the keyword   for  
country : India
Language : Hindi 

There are two more local language in which i like to contribute 
country : India
Language : Assamese , Bengali ..

suggest the keyword for these two also please ...

**Comment by ajphukan** [comment]
Are you following these code for starting two letters of keyword 

[Country code](http://www.bitmedia.com/cc/url1.htm)

Sorry for asking so many things ...

**Comment by hustcc** [comment]
Very nice, If you add the locale test cases into `tests/locales` dir, it will be prefact.

You can write test cases like `tests/locales/en.js`.

Thank you very much~

**Comment by ajphukan** [comment]
Okk .. @hustcc

**Comment by ajphukan** [comment]
Testing part will take time i will try do it as quickly as possible .

**Comment by ajphukan** [comment]
Thanks for approving.

**Pull request merged**
