### PR TITLE
[i18n] Adds Occitan to the locales

### PR DESCRIPTION
**Pull request by Quenty31**

### CODE REVIEW

**Comment by hustcc** [comment]
please help me add the test cases.

**Comment by Quenty31** [comment]
As soon as I have enough spare time I'll try to build the test cases!

**Comment by Quenty31** [comment]
Where do I find it?

**Comment by Quenty31** [comment]
Can I take it https://github.com/hustcc/timeago.js/blob/master/__tests__/lang/nl.spec.js ?

**Comment by hustcc** [comment]
The ci is error, because of the coverage rate is lower then before. You can write the testcase ref  https://github.com/hustcc/timeago.js/blob/master/__tests__/lang/nl.spec.js ?

**Comment by Quenty31** [comment]
> The ci is error, because of the coverage rate is lower then before. You can write the testcase ref https://github.com/hustcc/timeago.js/blob/master/__tests__/lang/nl.spec.js ?

Hello, just made a new Pull Request with the required file.

**Pull request closed without merging**
