### PR TITLE
Support --noImplicitAny option for TypeScript

### LINKED ISSUE #125: TypeScript errors with noImplicitAny: true
Hello. I'm having these errors when using `noImplicitAny: true` in `tsconfig.json`. Basicly it needs return type to defined, just not sure which one and how to do it. Is `timeago.d.ts` file created automatically?

```
ERROR in [at-loader] ./node_modules/timeago.js/timeago.d.ts:4:5 
    TS7013: Construct signature, which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in [at-loader] ./node_modules/timeago.js/timeago.d.ts:5:5 
    TS7013: Construct signature, which lacks return-type annotation, implicitly has an 'any' return type.
```

### PR DESCRIPTION
**Pull request by likerRr**
Fixes #125

### CODE REVIEW

**Comment by hustcc** [comment]
v3.0.1 published.

What's your npm account, I can add the publish auth to you. 

Recently, China's Ching Ming Festival, I am preparing to change jobs also, so the response time is long, very sorry.

**Comment by likerRr** [comment]
Thanks, [alizurchik](https://www.npmjs.com/~alizurchik)

Wish you good luck with changing job!

**Comment by hustcc** [comment]
Done.

I have got the offer. 6, april will the first day. ^_^

**Comment by likerRr** [comment]
@hustcc it's great! Hope you still will be satisfied with the new position after a while

**Comment by GuskiS** [comment]
Thanks for the fix  :+1:

**Pull request merged**
