### PR TITLE
added Hungarian language

### PR DESCRIPTION
**Pull request by szilardka**
#19

### CODE REVIEW

**Comment by hustcc** [comment]
@kukac7  just discuss the translation. His translation is slightly different from yours.

**Comment by kukac7** [comment]
@hustcc @szilardka reference: https://github.com/moment/moment/blob/develop/locale/hu.js#L14-L40

**Comment by szilardka** [comment]
@kukac7 yep, that's what I have followed. In my opinion your version is not perfect, because 
_2 minutes ago_ translates to _2 perc_ and
_in 2 minutes_ translates to _2 perce_ but they should translate as follows:
_2 minutes ago_ > _2 perce_ (e.g. "Tim posted 2 minutes ago" / "Tim küldte 2 perce")
_in 2 minutes_ > _2 percen belül_  (e.g. "The train arrives in 2 minutes" / "A vonat 2 percen belül érkezik").

/cc @hustcc

**Comment by hustcc** [comment]
@kukac7 , so changed to @szilardka 's translation ?

**Comment by kukac7** [comment]
@hustcc ok 🙇

**Pull request merged**
