### PR TITLE
V2 updates

### PR DESCRIPTION
**Pull request by likerRr**
PR to [comment](https://github.com/hustcc/timeago.js/issues/67#issuecomment-247860122). It doesn't change internal work of timeago lib, but reorganizes its architecture.

### CODE REVIEW

**Comment by hustcc** [comment]
Great work^_^, but something:
1. `prototype` is one of the methods those can define an Object.
2. Why some private methods add on `prototype`.
3. The `format`, `render` method is not on global scope, add a `timeagoFactory` seem do nothing more.
   image

Only 4 API in the timeago instance.
4. `diffSec`

``` js
function diffSec(now, date) {
-  return (toDate(now)* - toDate(date).getTime()) / 1000;
+  return (toDate(now).getTime() - toDate(date).getTime()) / 1000;
}
```

**Comment by likerRr** [comment]
@hustcc Hi! Thank you for review
1. Sorry, what would you like to say?
2. JavaScript by its nature doesn't have `private` or `protected` properties. I don't see a problem to put them near the public methods. Even if someone will use them - up to him :) All public API is described on the readme page, that's enough. Which issues do you see here?
3. Answered [here](https://github.com/hustcc/timeago.js/issues/67#issuecomment-247916971). Also, factory method allows you to use library in only one right way. So never mind how will you call it:

``` javascript
const timeago = timeagoFactory();
// or
const timeago = new timeagoFactory();
```

Result will be the same. It's factory pattern.
4. There is no difference, because when you subtract from Date object, its internal `valueOf()` is called, which returns timestamp representation.

**Comment by likerRr** [comment]
[Private methods discussion on stackoverflow](http://stackoverflow.com/questions/55611/javascript-private-methods#comment11532733_55637)

**Comment by likerRr** [comment]
[Updated](https://github.com/hustcc/timeago.js/pull/68/commits/f58d64e3b715f5c30df6e16bf82c3410dde7ef9f) PR with correct jsdoc comments and `formatDiff` moved out of prototype

**Comment by hustcc** [comment]
I usage some codes from this PR.
1. `Code style`.
2. Rounded with a factory to avoid `global scope`.
3. Remove `getTime()` of Date instance for reduce of library size.

I don't use `prototype` to create Object, because it has long character length.

Learn much from your PR and you, I'am a starter of front-end development. ^_^

**Comment by likerRr** [comment]
@hustcc as a starter, you're doing well!

But you shouldn't avoid usage of prototype, it brings significant performance improvements in most of cases. But if your target is just to keep library size as minimal as it possible ignoring performance.. I think we can reduce it more ;)

**Comment by likerRr** [comment]
I think this PR could be closed, do you?

**Comment by hustcc** [comment]
OK, continue learning from it.

**Comment by hustcc** [comment]
Why `getNowDate`, `validateAndGetLocale`, `doRender` should be on prototype.

**Comment by likerRr** [comment]
Because they are shared across all the instances of `timeago`.

**Comment by hustcc** [comment]
So I extract some common methods. https://github.com/hustcc/timeago.js/blob/master/src/timeago.js

**Comment by likerRr** [comment]
@hustcc much better. Now it's more clear where are the public API and where are the private

**Pull request closed without merging**
